# Run all existing pixit updates

le_psm = 0x0023
psm_unsupported = 0x00f1
pts_bd_addr = "00:11:22:33:44:55"

BROADCAST_CODE = '0102680553F1415AA265BBAFC6EA03B8'
BROADCAST_ID = 0x123456

def get_pixit_updates():
    def safe_pixit_update(group, name, value_func):
        def wrapper():
            try:
                value = value_func() if callable(value_func) else value_func
                pts.update_pixit_param(group, name, value)
            except Exception as e:
                logging.error(f"Failed to update PIXIT param {group}/{name}: {e}")
        return TestFunc(wrapper)

    return [
        # AICS
        safe_update("AICS", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("AICS", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("AICS", "TSPX_time_guard", "180000"),
        safe_update("AICS", "TSPX_use_implicit_send", "TRUE"),
        safe_update("AICS", "TSPX_mtu_size", "23"),
        safe_update("AICS", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("AICS", "TSPX_delete_link_key", "FALSE"),
        safe_update("AICS", "TSPX_pin_code", "0000"),
        safe_update("AICS", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("AICS", "TSPX_delete_ltk", "TRUE"),
        safe_update("AICS", "TSPX_security_enabled", "FALSE"),
        safe_update("AICS", "TSPX_iut_ATT_transport", "ATT Bearer on LE Transport"),
        safe_update("AICS", "TSPX_bd_addr_iut", stack.gap.iut_addr_get_str),
        # ASCS
        safe_update("ASCS", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("ASCS", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("ASCS", "TSPX_time_guard", "180000"),
        safe_update("ASCS", "TSPX_use_implicit_send", "TRUE"),
        safe_update("ASCS", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("ASCS", "TSPX_delete_link_key", "FALSE"),
        safe_update("ASCS", "TSPX_pin_code", "0000"),
        safe_update("ASCS", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("ASCS", "TSPX_delete_ltk", "TRUE"),
        safe_update("ASCS", "TSPX_security_enabled", "FALSE"),
        safe_update("ASCS", "TSPX_iut_ATT_transport", "ATT Bearer on LE Transport"),
        # BAP
        safe_update("BAP", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("BAP", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("BAP", "TSPX_time_guard", "180000"),
        safe_update("BAP", "TSPX_use_implicit_send", "TRUE"),
        safe_update("BAP", "TSPX_mtu_size", "64"),
        safe_update("BAP", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("BAP", "TSPX_delete_link_key", "FALSE"),
        safe_update("BAP", "TSPX_pin_code", "0000"),
        safe_update("BAP", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("BAP", "TSPX_delete_ltk", "TRUE"),
        safe_update("BAP", "TSPX_security_enabled", "FALSE"),
        safe_update("BAP", "TSPX_iut_ATT_transport", "ATT Bearer on LE Transport"),
        safe_update("BAP", "TSPX_VS_Codec_ID", "ffff"),
        safe_update("BAP", "TSPX_VS_Company_ID", "ffff"),
        safe_update("BAP", "TSPX_broadcast_code", BROADCAST_CODE),
        safe_update("BAP", "TSPX_Broadcast_ID", BROADCAST_ID),
        safe_update("BAP", "TSPX_Codec_ID", "ffffffffff"),
        # BASS
        safe_update("BASS", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("BASS", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("BASS", "TSPX_time_guard", "180000"),
        safe_update("BASS", "TSPX_use_implicit_send", "TRUE"),
        safe_update("BASS", "TSPX_mtu_size", "64"),
        safe_update("BASS", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("BASS", "TSPX_delete_link_key", "FALSE"),
        safe_update("BASS", "TSPX_pin_code", "0000"),
        safe_update("BASS", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("BASS", "TSPX_delete_ltk", "TRUE"),
        safe_update("BASS", "TSPX_security_enabled", "FALSE"),
        safe_update("BASS", "TSPX_iut_ATT_transport", "ATT Bearer on LE Transport"),
        safe_update("BASS", "TSPX_broadcast_code", BROADCAST_CODE),
        safe_update("BASS", "TSPX_Sync_Timeout", "8000"),
        # CAP
        safe_update("CAP", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("CAP", "TSPX_Public_bd_addr_LT2", "000000000000"),
        safe_update("CAP", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("CAP", "TSPX_time_guard", "180000"),
        safe_update("CAP", "TSPX_use_implicit_send", "TRUE"),
        safe_update("CAP", "TSPX_tester_database_file",
                      r"C:\Program Files (x86)\Bluetooth SIG\Bluetooth PTS\Data\SIGDatabase\PTS_BASS_db.xml"),
        safe_update("CAP", "TSPX_mtu_size", "64"),
        safe_update("CAP", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("CAP", "TSPX_delete_link_key", "FALSE"),
        safe_update("CAP", "TSPX_pin_code", "0000"),
        safe_update("CAP", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("CAP", "TSPX_delete_ltk", "TRUE"),
        safe_update("CAP", "TSPX_security_enabled", "TRUE"),
        safe_update("CAP", "TSPX_iut_ATT_transport", "ATT Bearer on LE Transport"),
        safe_update("CAP", "TSPX_TARGET_ASE_CHARACTERISTIC", "SINK_ASE"),
        safe_update("CAP", "TSPX_TARGET_LATENCY", "TARGET_BALANCED_LATENCY_RELIABILITY"),
        safe_update("CAP", "TSPX_TARGET_PHY", "LE_2M_PHY"),
        safe_update("CAP", "TSPX_Codec_ID", "0600000000"),
        safe_update("CAP", "TSPX_VS_Codec_Specific_Configuration", "0001"),
        safe_update("CAP", "TSPX_VS_QoS_Framing", "UNFRAMING"),
        safe_update("CAP", "TSPX_VS_QoS_PHY", "2M_PHY"),
        safe_update("CAP", "TSPX_VS_QoS_SDU_Interval", "64"),
        safe_update("CAP", "TSPX_VS_QoS_Max_SDU", "10000"),
        safe_update("CAP", "TSPX_VS_QoS_Retransmission_Number", "2"),
        safe_update("CAP", "TSPX_VS_QoS_Max_Transport_Latency", "40"),
        safe_update("CAP", "TSPX_VS_QoS_Presentation_Delay", "40000"),
        safe_update("CAP", "TSPX_VS_Company_ID", "0000"),
        safe_update("CAP", "TSPX_VS_Codec_ID", "0000"),
        safe_update("CAP", "TSPX_METADATA_SELECTION", "USE_IXIT_VALUE_FOR_METADATA"),
        safe_update("CAP", "TSPX_METADATA_SINK", "03020200"),
        safe_update("CAP", "TSPX_METADATA_SOURCE", "03020200"),
        safe_update("CAP", "TSPX_broadcast_code", "0102680553F1415AA265BBAFC6EA03B8"),
        safe_update("CAP", "TSPX_Sync_Timeout", "20000"),
        safe_update("CAP", "TSPX_sirk", "838E680553F1415AA265BBAFC6EA03B8"),
        safe_update("CAP", "TSPX_STREAMING_DATA_CONFIRMATION_METHOD", "By Playing"),
        safe_update("CAP", "TSPX_CONTEXT_TYPE", "0002"),
        safe_update("CAP", "TSPX_Connection_Interval", "80"),
        safe_update("CAP", "TSPX_Extended_Adv_Interval_min", "1200"),
        safe_update("CAP", "TSPX_Extended_Adv_Interval_max", "1200"),
        safe_update("CAP", "TSPX_Periodic_Adv_Interval_min", "600"),
        safe_update("CAP", "TSPX_Periodic_Adv_Interval_max", "600"),
        safe_update("CAP", "TSPX_BST_CODEC_CONFIG", "16_2_1"),
        # CAS
        safe_update("CAS", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("CAS", "TSPX_Public_bd_addr_LT2", "000000000000"),
        safe_update("CAS", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("CAS", "TSPX_time_guard", "18000"),
        safe_update("CAS", "TSPX_use_implicit_send", "TRUE"),
        safe_update("CAS", "TSPX_tester_database_file",
            r"C:\Program Files (x86)\Bluetooth SIG\Bluetooth PTS\Data\SIGDatabase\PTS_BASS_db.xml"),
        safe_update("CAS", "TSPX_mtu_size", "64"),
        safe_update("CAS", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("CAS", "TSPX_delete_link_key", "TRUE"),
        safe_update("CAS", "TSPX_pin_code", "0000"),
        safe_update("CAS", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("CAS", "TSPX_delete_ltk", "TRUE"),
        safe_update("CAS", "TSPX_security_enabled", "TRUE"),
        safe_update("CAS", "TSPX_iut_ATT_transport", "ATT Bearer on LE Transport"),
        # CCP
        safe_update("CCP", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("CCP", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("CCP", "TSPX_time_guard", "180000"),
        safe_update("CCP", "TSPX_use_implicit_send", "TRUE"),
        safe_update("CCP", "TSPX_tester_database_file",
            r"C:\Program Files (x86)\Bluetooth SIG\Bluetooth PTS\Data\SIGDatabase\PTS_CCP_db.xml"),
        safe_update("CCP", "TSPX_mtu_size", "23"),
        safe_update("CCP", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("CCP", "TSPX_delete_link_key", "FALSE"),
        safe_update("CCP", "TSPX_pin_code", "0000"),
        safe_update("CCP", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("CCP", "TSPX_delete_ltk", "TRUE"),
        safe_update("CCP", "TSPX_security_enabled", "TRUE"),
        safe_update("CCP", "TSPX_iut_GAP_connection_role", "Peripheral"),
        safe_update("CCP", "TSPX_iut_ATT_transport", "ATT Bearer on LE Transport"),
        # CSIP
        safe_update("CSIP", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("CSIP", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("CSIP", "TSPX_time_guard", "180000"),
        safe_update("CSIP", "TSPX_use_implicit_send", "TRUE"),
        safe_update("CSIP", "TSPX_tester_database_file",
                      r"C:\Program Files (x86)\Bluetooth SIG\Bluetooth PTS\Data\SIGDatabase\PTS_CSIP_db.xml"),
        safe_update("CSIP", "TSPX_mtu_size", "23"),
        safe_update("CSIP", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("CSIP", "TSPX_delete_link_key", "FALSE"),
        safe_update("CSIP", "TSPX_pin_code", "0000"),
        safe_update("CSIP", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("CSIP", "TSPX_delete_ltk", "TRUE"),
        safe_update("CSIP", "TSPX_security_enabled", "FALSE"),
        safe_update("CSIP", "TSPX_target_service", "5F03"),
        safe_update("CSIP", "TSPX_set_size", "3"),
        safe_update("CSIP", "TSPX_sirk", "838E680553F1415AA265BBAFC6EA03B8"),
        safe_update("CSIP", "TSPX_private_addr_int", "120000"),
        safe_update("CSIP", "TSPX_iut_ATT_transport", "ATT Bearer on LE Transport"),
        # CSIS
        safe_update("CSIS", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("CSIS", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("CSIS", "TSPX_time_guard", "18000"),
        safe_update("CSIS", "TSPX_use_implicit_send", "TRUE"),
        safe_update("CSIS", "TSPX_tester_database_file",
            r"C:\Program Files (x86)\Bluetooth SIG\Bluetooth PTS\Data\SIGDatabase\PTS_CSIP_db.xml"),
        safe_update("CSIS", "TSPX_mtu_size", "23"),
        safe_update("CSIS", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("CSIS", "TSPX_delete_link_key", "FALSE"),
        safe_update("CSIS", "TSPX_pin_code", "0000"),
        safe_update("CSIS", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("CSIS", "TSPX_delete_ltk", "TRUE"),
        safe_update("CSIS", "TSPX_security_enabled", "TRUE"),
        safe_update("CSIS", "TSPX_Lock_Timeout_Seconds", "60"),
        safe_update("CSIS", "TSPX_iut_ATT_transport", "ATT Bearer on LE Transport"),
        # DFUM
        safe_update("DFUM", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("DFUM", "TSPX_time_guard", "300000"),
        safe_update("DFUM", "TSPX_use_implicit_send", "TRUE"),
        safe_update("DFUM", "TSPX_tester_database_file",
                      r"C:\Program Files\Bluetooth SIG\Bluetooth PTS\Data\SIGDatabase\PTS_SMPP_db.xml"),
        safe_update("DFUM", "TSPX_mtu_size", "23"),
        safe_update("DFUM", "TSPX_delete_link_key", "TRUE"),
        safe_update("DFUM", "TSPX_delete_ltk", "TRUE"),
        safe_update("DFUM", "TSPX_security_enabled", "FALSE"),
        safe_update("DFUM", "TSPX_iut_setup_att_over_br_edr", "FALSE"),
        safe_update("DFUM", "TSPX_scan_interval", "30"),
        safe_update("DFUM", "TSPX_scan_window", "30"),
        safe_update("DFUM", "TSPX_scan_filter", "00"),
        safe_update("DFUM", "TSPX_advertising_interval_min", "160"),
        safe_update("DFUM", "TSPX_advertising_interval_max", "160"),
        safe_update("DFUM", "TSPX_tester_OOB_information", "F87F"),
        safe_update("DFUM", "TSPX_device_uuid", "00000000000000000000000000000000"),
        safe_update("DFUM", "TSPX_device_uuid2", "001BDC0810210B0E0A0C000B0E0A0C00"),
        safe_update("DFUM", "TSPX_use_pb_gatt_bearer", "FALSE"),
        safe_update("DFUM", "TSPX_iut_comp_data_page", "2"),
        safe_update("DFUM", "TSPX_oob_state_change", "FALSE"),
        safe_update("DFUM", "TSPX_enable_IUT_provisioner", "FALSE"),
        safe_update("DFUM", "TSPX_Procedure_Timeout", "60"),
        safe_update("DFUM", "TSPX_Client_BLOB_ID", "1100000000000011"),
        safe_update("DFUM", "TSPX_Client_BLOB_Data", r"data.txt"),
        safe_update("DFUM", "TSPX_TTL", "2"),
        safe_update("MBTM", "TSPX_Server_Timeout_Base", "5"),
        safe_update("DFUM", "TSPX_Firmware_ID", "11000011"),
        safe_update("DFUM", "TSPX_Firmware_Metadata", "1100000000000011"),
        safe_update("DFUM", "TSPX_Firmware_Update_URI", "http://www.dummy.com"),
        safe_update("DFUM", "TSPX_New_Firmware_Image", r"data2.txt"),
        safe_update("DFUM", "TSPX_Update_Firmware_Image_Index", "0"),
        # DIS
        safe_update("DIS", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("DIS", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("DIS", "TSPX_time_guard", "180000"),
        safe_update("DIS", "TSPX_use_implicit_send", "TRUE"),
        safe_update("DIS", "TSPX_mtu_size", "23"),
        safe_update("DIS", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("DIS", "TSPX_delete_link_key", "TRUE"),
        safe_update("DIS", "TSPX_pin_code", "0000"),
        safe_update("DIS", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("DIS", "TSPX_delete_ltk", "TRUE"),
        safe_update("DIS", "TSPX_security_enabled", "FALSE"),
        safe_update("DIS", "TSPX_iut_setup_att_over_br_edr", "FALSE"),
        safe_update("DIS", "TSPX_tester_appearance", "0000"),
        # GAP
        safe_update("GAP", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("GAP", "TSPX_bd_addr_PTS", "C000DEADBEEF"),
        safe_update("GAP", "TSPX_broadcaster_class_of_device", "100104"),
        safe_update("GAP", "TSPX_observer_class_of_device", "100104"),
        safe_update("GAP", "TSPX_central_class_of_device", "100104"),
        safe_update("GAP", "TSPX_security_enabled", "FALSE"),
        safe_update("GAP", "TSPX_delete_link_key", "FALSE"),
        safe_update("GAP", "TSPX_iut_setup_att_over_br_edr", "FALSE"),
        safe_update("GAP", "TSPX_mtu_size", "23"),
        safe_update("GAP", "TSPX_delete_ltk", "FALSE"),
        safe_update("GAP", "TSPX_pin_code", "0000"),
        safe_update("GAP", "TSPX_time_guard", "300000"),
        safe_update("GAP", "TSPX_use_implicit_send", "TRUE"),
        safe_update("GAP", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("GAP", "TSPX_secure_simple_pairing_pass_key_confirmation",
                      "FALSE"),
        safe_update("GAP", "TSPX_using_public_device_address", "TRUE"),
        safe_update("GAP", "TSPX_using_random_device_address", "FALSE"),
        safe_update("GAP", "TSPX_lim_adv_timeout", "30720"),
        safe_update("GAP", "TSPX_gen_disc_adv_min", "30720"),
        safe_update("GAP", "TSPX_lim_disc_scan_min", "10240"),
        safe_update("GAP", "TSPX_gen_disc_scan_min", "10240"),
        safe_update("GAP", "TSPX_database_file", "Database-GAP.sig"),
        safe_update("GAP", "TSPX_iut_rx_mtu", "23"),
        safe_update("GAP", "TSPX_iut_private_address_interval", "30000"),
        safe_update("GAP", "TSPX_iut_privacy_enabled", "FALSE"),
        safe_update("GAP", "TSPX_psm", "1001"),
        safe_update("GAP", "TSPX_psm_2", "2001"),
        safe_update("GAP", "TSPX_iut_valid_connection_interval_min", "00C8"),
        safe_update("GAP", "TSPX_iut_valid_connection_interval_max", "03C0"),
        safe_update("GAP", "TSPX_iut_valid_connection_latency", "0006"),
        safe_update("GAP", "TSPX_iut_valid_timeout_multiplier", "0962"),
        safe_update("GAP", "TSPX_Tgap_conn_param_timeout", "30000"),
        safe_update("GAP", "TSPX_iut_invalid_connection_interval_min", "0008"),
        safe_update("GAP", "TSPX_iut_invalid_connection_interval_max", "00AA"),
        safe_update("GAP", "TSPX_iut_invalid_connection_latency", "0000"),
        safe_update("GAP", "TSPX_iut_invalid_conn_update_supervision_timeout", "0800"),
        safe_update("GAP", "TSPX_LE_scan_interval", "0010"),
        safe_update("GAP", "TSPX_LE_scan_window", "0010"),
        safe_update("GAP", "TSPX_con_interval_min", "0032"),
        safe_update("GAP", "TSPX_con_interval_max", "0046"),
        safe_update("GAP", "TSPX_con_latency", "0001"),
        safe_update("GAP", "TSPX_supervision_timeout", "07D0"),
        safe_update("GAP", "TSPX_minimum_ce_length", "0000"),
        safe_update("GAP", "TSPX_maximum_ce_length", "0000"),
        safe_update("GAP", "TSPX_conn_update_int_min", "0032"),
        safe_update("GAP", "TSPX_conn_update_int_max", "0046"),
        safe_update("GAP", "TSPX_conn_update_peripheral_latency", "0001"),
        safe_update("GAP", "TSPX_conn_update_supervision_timeout", "01F4"),
        safe_update("GAP", "TSPX_pairing_before_service_request", "FALSE"),
        safe_update("GAP", "TSPX_iut_mandates_mitm", "FALSE"),
        safe_update("GAP", "TSPX_encryption_before_service_request", "FALSE"),
        safe_update("GAP", "TSPX_tester_appearance", "0000"),
        safe_update("GAP", "TSPX_iut_device_IRK_for_resolvable_privacy_address_generation_procedure",
                      "00000000000000000000000000000000"),
        safe_update("GAP", "TSPX_tester_device_IRK_for_resolvable_privacy_address_generation_procedure",
                      "0123456789ABCDEF0123456789ABCDEF"),
        safe_update("GAP",
                      "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("GAP", "TSPX_Tgap_104", "60000"),
        safe_update("GAP", "TSPX_URI", "176769746875622E636F6D2F6175746F2D707473"),
        safe_update("GAP", "TSPX_periodic_advertising_data",
                      binascii.hexlify((chr(len(periodic_data[1]) + 1) + chr(periodic_data[0]) +
                                        periodic_data[1]).encode())),
        safe_update("GAP", "TSPX_Min_Encryption_Key_Size", "07"),
        safe_update("GAP", "TSPX_broadcast_code", "8ED03323D1205E2D58191BF6285C3182"),
        safe_update("GAP", "TSPX_gap_iut_role", "Peripheral"),
        safe_update("GAP", "TSPX_advertising_data", ad_pixit),
        safe_update("GAP", "TSPX_psm_sm4l2", format(br_psm, '04x')),
        safe_update("GAP", "TSPX_psm_sm4l3", format(br_psm, '04x')),
        safe_update("GAP", "TSPX_psm_sm4l4", format(br_psm, '04x')),
        # GATT
        safe_update("GATT", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("GATT", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("GATT", "TSPX_security_enabled", "FALSE"),
        safe_update("GATT", "TSPX_delete_link_key", "TRUE"),
        safe_update("GATT", "TSPX_time_guard", "180000"),
        safe_update("GATT", "TSPX_selected_handle", "0012"),
        safe_update("GATT", "TSPX_use_implicit_send", "TRUE"),
        safe_update("GATT", "TSPX_iut_use_dynamic_bd_addr", "FALSE"),
        safe_update("GATT", "TSPX_iut_setup_att_over_br_edr", "FALSE"),
        safe_update("GATT", "TSPX_iut_is_client_periphral", "TRUE"),
        safe_update("GATT", "TSPX_iut_is_server_central", "FALSE"),
        safe_update("GATT", "TSPX_mtu_size", "23"),
        safe_update("GATT", "TSPX_pin_code", "0000"),
        safe_update("GATT", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("GATT", "TSPX_delete_ltk", "TRUE"),
        safe_update("GATT", "TSPX_tester_appearance", "0000"),
        safe_update("GATT", "TSPX_bearer_for_le", "EATT"),
        # HAP
        safe_update("HAP", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("HAP", "TSPX_Public_bd_addr_LT2", "000000000000"),
        safe_update("HAP", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("HAP", "TSPX_time_guard", "180000"),
        safe_update("HAP", "TSPX_use_implicit_send", "TRUE"),
        safe_update("HAP", "TSPX_tester_database_file",
            r"C:\Program Files (x86)\Bluetooth SIG\Bluetooth PTS\Data\SIGDatabase\PTS_HAS_db.xml"),
        safe_update("HAP", "TSPX_mtu_size", "64"),
        safe_update("HAP", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("HAP", "TSPX_delete_link_key", "FALSE"),
        safe_update("HAP", "TSPX_pin_code", "0000"),
        safe_update("HAP", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("HAP", "TSPX_delete_ltk", "TRUE"),
        safe_update("HAP", "TSPX_security_enabled", "TRUE"),
        safe_update("HAP", "TSPX_iut_ATT_transport", "ATT Bearer on LE Transport"),
        safe_update("HAP", "TSPX_sirk", "838E680553F1415AA265BBAFC6EA03B8"),
        safe_update("HAP", "TSPX_Connection_Interval", "120"),
        safe_update("HAP", "TSPX_Extended_Adv_Interval_min", "1200"),
        safe_update("HAP", "TSPX_Extended_Adv_Interval_max", "1200"),
        safe_update("HAP", "TSPX_Periodic_Adv_Interval_min", "600"),
        safe_update("HAP", "TSPX_Periodic_Adv_Interval_max", "600"),
        safe_update("HAP", "TSPX_TARGET_LATENCY", "TARGET_LOWER_LATENCY"),
        safe_update("HAP", "TSPX_TARGET_PHY", "LE_2M_PHY"),
        safe_update("HAP", "TSPX_largest_preset_index", str(max_index)),
        safe_update("HAP", "TSPX_num_presets", str(num_presets)),
        # HAS
        safe_update("HAS", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("HAS", "TSPX_Public_bd_addr_LT2", "000000000000"),
        safe_update("HAS", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("HAS", "TSPX_time_guard", "180000"),
        safe_update("HAS", "TSPX_use_implicit_send", "TRUE"),
        safe_update("HAS", "TSPX_tester_database_file",
            r"C:\Program Files (x86)\Bluetooth SIG\Bluetooth PTS\Data\SIGDatabase\PTS_HAS_db.xml"),
        safe_update("HAS", "TSPX_mtu_size", "49"),
        safe_update("HAS", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("HAS", "TSPX_delete_link_key", "FALSE"),
        safe_update("HAS", "TSPX_pin_code", "0000"),
        safe_update("HAS", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("HAS", "TSPX_delete_ltk", "TRUE"),
        safe_update("HAS", "TSPX_security_enabled", "TRUE"),
        safe_update("HAS", "TSPX_iut_ATT_transport", "ATT Bearer on LE Transport"),
        safe_update("HAS", "TSPX_Connection_Interval", "120"),
        safe_update("HAS", "TSPX_largest_preset_index", str(max_index)),
        safe_update("HAS", "TSPX_num_presets", str(num_presets)),
        safe_update("HAS", "TSPX_available_preset_index", available_presets_str),
        safe_update("HAS", "TSPX_unavailable_preset_index", unavailable_presets_str),
        safe_update("HAS", "TSPX_writable_preset_index", writable_presets_str),
        safe_update("HAS", "TSPX_unwritable_preset_index", unwritable_presets_str),
        # IAS
        safe_update("IAS", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("IAS", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("IAS", "TSPX_time_guard", "180000"),
        safe_update("IAS", "TSPX_use_implicit_send", "TRUE"),
        safe_update("IAS", "TSPX_mtu_size", "23"),
        safe_update("IAS", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("IAS", "TSPX_delete_link_key", "FALSE"),
        safe_update("IAS", "TSPX_pin_code", "0000"),
        safe_update("IAS", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("IAS", "TSPX_delete_ltk", "FALSE"),
        safe_update("IAS", "TSPX_security_enabled", "FALSE"),
        safe_update("IAS", "TSPX_iut_setup_att_over_br_edr", "FALSE"),
        safe_update("IAS", "TSPX_tester_appearance", "0000"),
        # L2CAP
        safe_update("L2CAP", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("L2CAP", "TSPX_security_enabled", "FALSE"),
        safe_update("L2CAP", "TSPX_delete_link_key", "FALSE"),
        safe_update("L2CAP", "TSPX_pin_code", "0000"),
        safe_update("L2CAP", "TSPX_delete_ltk", "FALSE"),
        safe_update("L2CAP", "TSPX_l2ca_inmtu", "02A0"),
        safe_update("L2CAP", "TSPX_iut_supported_max_channels", "5"),
        safe_update("L2CAP", "TSPX_tester_mps", "0017"),
        safe_update("L2CAP", "TSPX_tester_mtu", "02A0"),
        safe_update("L2CAP", "TSPX_iut_role_initiator", "True"),
        safe_update("L2CAP", "TSPX_spsm", "0000"),
        safe_update("L2CAP", "TSPX_psm", "0001"),
        safe_update("L2CAP", "TSPX_psm_unsupported", "0000"),
        safe_update("L2CAP", "TSPX_psm_authentication_required", "00F2"),
        safe_update("L2CAP", "TSPX_psm_authorization_required", "00F3"),
        safe_update("L2CAP", "TSPX_psm_encryption_key_size_required", "00F4"),
        safe_update("L2CAP", "TSPX_time_guard", "180000"),
        safe_update("L2CAP", "TSPX_timer_rtx", "10000"),
        safe_update("L2CAP", "TSPX_timer_rtx_max", "1000"),
        safe_update("L2CAP", "TSPX_timer_rtx_min", "60000"),
        safe_update("L2CAP", "TSPX_use_implicit_send", "TRUE"),
        safe_update("L2CAP", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("L2CAP", "TSPX_iut_SDU_size_in_bytes", "144"),
        safe_update("L2CAP", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("L2CAP", "TSPX_generate_local_busy", "TRUE"),
        safe_update("L2CAP", "TSPX_l2ca_cbmps_min", "0040"),
        safe_update("L2CAP", "TSPX_l2ca_cbmps_max", "0100"),
        safe_update("L2CAP", "TSPX_psm_encryption_required", format(le_psm, '04x')),
        safe_update("L2CAP", "TSPX_l2ca_num_concurrent_credit_based_connections", "2"),
        safe_update("L2CAP", "TSPX_l2ca_cbmtu_min", format(64, '04x')),
        safe_update("L2CAP", "TSPX_l2ca_cbmtu_max", format(256, '04x')),
        # MCP
        safe_update("MCP", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("MCP", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("MCP", "TSPX_time_guard", "180000"),
        safe_update("MCP", "TSPX_use_implicit_send", "TRUE"),
        safe_update("MCP", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("MCP", "TSPX_delete_link_key", "FALSE"),
        safe_update("MCP", "TSPX_mtu_size", 23),
        safe_update("MCP", "TSPX_pin_code", "0000"),
        safe_update("MCP", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("MCP", "TSPX_delete_ltk", "TRUE"),
        safe_update("MCP", "TSPX_security_enabled", "TRUE"),
        safe_update("MCP", "TSPX_MCS_Media_Player_Name", "GMCS Player"),
        # MCS
        safe_update("MCS", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("MCS", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("MCS", "TSPX_time_guard", "180000"),
        safe_update("MCS", "TSPX_use_implicit_send", "TRUE"),
        safe_update("MCS", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("MCS", "TSPX_mtu_size", 23),
        safe_update("MCS", "TSPX_delete_link_key", "FALSE"),
        safe_update("MCS", "TSPX_pin_code", "0000"),
        safe_update("MCS", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("MCS", "TSPX_delete_ltk", "TRUE"),
        safe_update("MCS", "TSPX_security_enabled", "FALSE"),
        safe_update("MCS", "TSPX_Track_Name", "Track"),
        safe_update("MCS", "TSPX_Artist_Name", "Artist"),
        safe_update("MCS", "TSPX_Album_Name", "Album"),
        safe_update("MCS", "TSPX_Group_Name", "Group"),
        safe_update("MCS", "TSPX_Earliest_Year", "1999"),
        safe_update("MCS", "TSPX_Latest_Year", "2000"),
        safe_update("MCS", "TSPX_Genre", "Genre"),
        # MICP
        safe_update("MICP", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("MICP", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("MICP", "TSPX_time_guard", "180000"),
        safe_update("MICP", "TSPX_use_implicit_send", "TRUE"),
        safe_update("MICP", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("MICP", "TSPX_mtu_size", 23),
        safe_update("MICP", "TSPX_delete_link_key", "FALSE"),
        safe_update("MICP", "TSPX_pin_code", "0000"),
        safe_update("MICP", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("MICP", "TSPX_delete_ltk", "FALSE"),
        safe_update("MICP", "TSPX_security_enabled", "FALSE"),
        # MICS
        safe_update("MICS", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("MICS", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("MICS", "TSPX_time_guard", "180000"),
        safe_update("MICS", "TSPX_use_implicit_send", "TRUE"),
        safe_update("MICS", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("MICS", "TSPX_mtu_size", 23),
        safe_update("MICS", "TSPX_delete_link_key", "FALSE"),
        safe_update("MICS", "TSPX_pin_code", "0000"),
        safe_update("MICS", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("MICS", "TSPX_delete_ltk", "TRUE"),
        safe_update("MICS", "TSPX_security_enabled", "TRUE"),
        # MMDL
        safe_update("MMDL", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("MMDL", "TSPX_time_guard", "300000"),
        safe_update("MMDL", "TSPX_use_implicit_send", "TRUE"),
        safe_update("MMDL", "TSPX_mtu_size", "23"),
        safe_update("MMDL", "TSPX_delete_link_key", "TRUE"),
        safe_update("MMDL", "TSPX_delete_ltk", "TRUE"),
        safe_update("MMDL", "TSPX_security_enabled", "FALSE"),
        safe_update("MMDL", "TSPX_iut_setup_att_over_br_edr", "FALSE"),
        safe_update("MMDL", "TSPX_scan_interval", "30"),
        safe_update("MMDL", "TSPX_scan_window", "30"),
        safe_update("MMDL", "TSPX_scan_filter", "00"),
        safe_update("MMDL", "TSPX_advertising_interval_min", "160"),
        safe_update("MMDL", "TSPX_advertising_interval_max", "160"),
        safe_update("MMDL", "TSPX_tester_OOB_information", "F87F"),
        safe_update("MMDL", "TSPX_device_uuid", "00000000000000000000000000000000"),
        safe_update("MMDL", "TSPX_device_uuid2", "001BDC0810210B0E0A0C000B0E0A0C00"),
        safe_update("MMDL", "TSPX_use_pb_gatt_bearer", "FALSE"),
        safe_update("MMDL", "TSPX_oob_state_change", "FALSE"),
        safe_update("MMDL", "TSPX_sensor_property_ids", "1,0069,0010,FFF0"),
        safe_update("MMDL", "TSPX_enable_IUT_provisioner", "FALSE"),
        safe_update("MMDL", "TSPX_cadence_property_IDs", "1,0069,0010,FFF0"),
        safe_update("MMDL", "TSPX_iut_comp_data_page", "1"),
        # OTS
        safe_update("OTS", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("OTS", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("OTS", "TSPX_time_guard", "180000"),
        safe_update("OTS", "TSPX_use_implicit_send", "TRUE"),
        safe_update("OTS", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("OTS", "TSPX_mtu_size", 23),
        safe_update("OTS", "TSPX_delete_link_key", "FALSE"),
        safe_update("OTS", "TSPX_pin_code", "0000"),
        safe_update("OTS", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("OTS", "TSPX_delete_ltk", "TRUE"),
        safe_update("OTS", "TSPX_security_enabled", "TRUE"),
        safe_update("OTS", "TSPX_iut_object_name", "Object 1 with very long name"),
        safe_update("OTS", "TSPX_iut_object_size_create", "100"),
        safe_update("OTS", "TSPX_iut_object_read_offset", "20"),
        safe_update("OTS", "TSPX_iut_object_write_offset", "20"),
        safe_update("OTS", "TSPX_iut_object_write_length", "20"),
        # PACS
        safe_update("PACS", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("PACS", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("PACS", "TSPX_time_guard", "180000"),
        safe_update("PACS", "TSPX_use_implicit_send", "TRUE"),
        safe_update("PACS", "TSPX_mtu_size", "60"),
        safe_update("PACS", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("PACS", "TSPX_delete_link_key", "FALSE"),
        safe_update("PACS", "TSPX_delete_ltk", "TRUE"),
        safe_update("PACS", "TSPX_security_enabled", "FALSE"),
        safe_update("PACS", "TSPX_iut_ATT_transport", "ATT Bearer on LE Transport"),
        # PBP
        safe_update("PBP", "TSPX_time_guard", "180000"),
        safe_update("PBP", "TSPX_use_implicit_send", "TRUE"),
        safe_update("PBP", "TSPX_broadcast_code", BROADCAST_CODE),
        safe_update("PBP", "TSPX_Program_Info", PROGRAM_INFO),
        safe_update("PBP", "TSPX_Broadcast_Name", BROADCAST_NAME),
        # SDP
        safe_update("SDP", "TSPX_security_enabled", "FALSE"),
        safe_update("SDP", "TSPX_delete_link_key", "FALSE"),
        safe_update("SDP", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("SDP", "TSPX_class_of_device_pts", "200404"),
        safe_update("SDP", "TSPX_pin_code", "0000"),
        safe_update("SDP", "TSPX_time_guard", "200000"),
        safe_update("SDP", "TSPX_use_implicit_send", "TRUE"),
        safe_update("SDP", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("SDP", "TSPX_sdp_service_search_pattern", "0100"),
        safe_update("SDP", "TSPX_sdp_unsupported_service", "EEEE"),
        safe_update("SDP", "TSPX_sdp_additional_protocol_descriptor_list", ""),
        safe_update("SDP", "TSPX_sdp_bluetooth_profile_descriptor_list", ""),
        safe_update("SDP", "TSPX_sdp_browse_group_list", ""),
        safe_update("SDP", "TSPX_sdp_client_exe_url", ""),
        safe_update("SDP", "TSPX_sdp_documentation_url", ""),
        safe_update("SDP", "TSPX_sdp_icon_url", ""),
        safe_update("SDP", "TSPX_sdp_language_base_attribute_id_list", ""),
        safe_update("SDP", "TSPX_sdp_protocol_descriptor_list", ""),
        safe_update("SDP", "TSPX_sdp_provider_name", ""),
        safe_update("SDP", "TSPX_sdp_service_availability", ""),
        safe_update("SDP", "TSPX_sdp_service_data_base_state", "0100"),
        safe_update("SDP", "TSPX_sdp_service_description", ""),
        safe_update("SDP", "TSPX_sdp_service_id", ""),
        safe_update("SDP", "TSPX_sdp_service_info_time_to_live", ""),
        safe_update("SDP", "TSPX_sdp_version_number_list", "0100"),
        safe_update("SDP", "TSPX_sdp_service_name", ""),
        safe_update("SDP", "TSPX_sdp_service_record_state", ""),
        safe_update("SDP", "TSPX_sdp_unsupported_attribute_id", "EEEE"),
        # SM
        safe_update("SM", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("SM", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("SM", "TSPX_time_guard", "180000"),
        safe_update("SM", "TSPX_use_implicit_send", "TRUE"),
        safe_update("SM", "TSPX_new_key_failed_count", "0"),
        safe_update("SM", "TSPX_Bonding_Flags", "00"),
        safe_update("SM", "TSPX_ATTR_HANDLE", "0000"),
        safe_update("SM", "TSPX_ATTR_VALUE", "0000000000000000"),
        safe_update("SM", "TSPX_Min_Encryption_Key_Length", "07"),
        safe_update("SM", "TSPX_OOB_Data", "0000000000000000FE12036E5A889F4D"),
        safe_update("SM", "TSPX_tester_role_optional", "L2CAP_ROLE_INITIATOR"),
        # TBS
        safe_update("TBS", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("TBS", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("TBS", "TSPX_time_guard", "180000"),
        safe_update("TBS", "TSPX_use_implicit_send", "TRUE"),
        safe_update("TBS", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("TBS", "TSPX_mtu_size", 23),
        safe_update("TBS", "TSPX_delete_link_key", "FALSE"),
        safe_update("TBS", "TSPX_pin_code", "0000"),
        safe_update("TBS", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("TBS", "TSPX_delete_ltk", "TRUE"),
        safe_update("TBS", "TSPX_security_enabled", "FALSE"),
        safe_update("TBS", "TSPX_Signal_Strength_Reporting_Interval", 10),
        safe_update("TBS", "TSPX_Incoming_Call_Target_Caller_ID", "tel:+19991111234"),
        safe_update("TBS", "TSPX_Incoming_friendly_name", "tel:+19991110011"),
        safe_update("TBS", "TSPX_Outgoing_uri", "tel:+19991111234"),
        safe_update("TBS", "TSPX_Outgoing_uri2", "tel:+19991111235"),
        # TMAP
        safe_update("TMAP", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("TMAP", "TSPX_Public_bd_addr_LT2", "000000000000"),
        safe_update("TMAP", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("TMAP", "TSPX_time_guard", "180000"),
        safe_update("TMAP", "TSPX_use_implicit_send", "TRUE"),
        safe_update("TMAP", "TSPX_tester_database_file",
                      r"C:\Program Files (x86)\Bluetooth SIG\Bluetooth PTS\Data\SIGDatabase\PTS_TMAP_db.xml"),
        safe_update("TMAP", "TSPX_mtu_size", "64"),
        safe_update("TMAP", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("TMAP", "TSPX_delete_link_key", "FALSE"),
        safe_update("TMAP", "TSPX_pin_code", "0000"),
        safe_update("TMAP", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("TMAP", "TSPX_delete_ltk", "TRUE"),
        safe_update("TMAP", "TSPX_security_enabled", "TRUE"),
        safe_update("TMAP", "TSPX_iut_ATT_transport", "ATT Bearer on LE Transport"),
        safe_update("TMAP", "TSPX_sirk", "838E680553F1415AA265BBAFC6EA03B8"),
        safe_update("TMAP", "TSPX_Connection_Interval", "120"),
        safe_update("TMAP", "TSPX_Extended_Adv_Interval_min", "1200"),
        safe_update("TMAP", "TSPX_Extended_Adv_Interval_max", "1200"),
        safe_update("TMAP", "TSPX_Periodic_Adv_Interval_min", "600"),
        safe_update("TMAP", "TSPX_Periodic_Adv_Interval_max", "600"),
        safe_update("TMAP", "TSPX_TARGET_LATENCY", "TARGET_LOWER_LATENCY"),
        safe_update("TMAP", "TSPX_TARGET_PHY", "LE_2M_PHY"),
        # VCP
        safe_update("VCP", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("VCP", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("VCP", "TSPX_time_guard", "180000"),
        safe_update("VCP", "TSPX_use_implicit_send", "TRUE"),
        safe_update("VCP", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("VCP", "TSPX_mtu_size", 23),
        safe_update("VCP", "TSPX_delete_link_key", "FALSE"),
        safe_update("VCP", "TSPX_pin_code", "0000"),
        safe_update("VCP", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("VCP", "TSPX_delete_ltk", "FALSE"),
        safe_update("VCP", "TSPX_security_enabled", "FALSE"),
        # VCS
        safe_update("VCS", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("VCS", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("VCS", "TSPX_time_guard", "180000"),
        safe_update("VCS", "TSPX_use_implicit_send", "TRUE"),
        safe_update("VCS", "TSPX_mtu_size", "23"),
        safe_update("VCS", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("VCS", "TSPX_delete_link_key", "FALSE"),
        safe_update("VCS", "TSPX_pin_code", "0000"),
        safe_update("VCS", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("VCS", "TSPX_delete_ltk", "TRUE"),
        safe_update("VCS", "TSPX_security_enabled", "FALSE"),
        # VOCS
        safe_update("VOCS", "TSPX_bd_addr_iut", "DEADBEEFDEAD"),
        safe_update("VOCS", "TSPX_iut_device_name_in_adv_packet_for_random_address", ""),
        safe_update("VOCS", "TSPX_time_guard", "180000"),
        safe_update("VOCS", "TSPX_use_implicit_send", "TRUE"),
        safe_update("VOCS", "TSPX_mtu_size", "23"),
        safe_update("VOCS", "TSPX_secure_simple_pairing_pass_key_confirmation", "FALSE"),
        safe_update("VOCS", "TSPX_delete_link_key", "FALSE"),
        safe_update("VOCS", "TSPX_pin_code", "0000"),
        safe_update("VOCS", "TSPX_use_dynamic_pin", "FALSE"),
        safe_update("VOCS", "TSPX_delete_ltk", "TRUE"),
        safe_update("VOCS", "TSPX_security_enabled", "FALSE"),
        safe_update("VOCS", "TSPX_iut_ATT_transport", "ATT Bearer on LE Transport"),
    ]

def main(self, _args=None):
    """Main.
    Args:
        _args: namespace of predefined or parsed earlier args
    """
    errmsg = self.parse_config_and_args(_args)
    if errmsg != '':
        sys.exit(errmsg)

    # root privileges only needed for native mode.
    if have_admin_rights():
        if not self.args.sudo:
            sys.exit("Please do not run this program as root.")
    elif self.args.sudo:
        sys.exit("Please run this program as root.")

    os.makedirs(self.file_paths["TMP_DIR"], exist_ok=True)

    self.load_test_case_database()

    init_pts(self.args, self.ptses)


